<?php $editando = !empty($compra['com_id']); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar compra' : 'Registrar compra' ?></h1><p class="text-secondary mb-0">Guarde os dados da aquisição e validade.</p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/medicamentos/compras')) ?>">Voltar</a></div>
<?php if (!$medicamentos): ?><div class="alert alert-warning">Cadastre um medicamento antes de registrar uma compra. <a href="<?= escapar(url('/medicamentos/formulario')) ?>">Cadastrar agora</a>.</div><?php else: ?>
<form action="<?= escapar(url('/medicamentos/compras/salvar')) ?>" method="post"><?= campo_csrf() ?><?php if ($editando): ?><input type="hidden" name="com_id" value="<?= (int) $compra['com_id'] ?>"><?php endif; ?>
<div class="card"><div class="card-body p-4"><div class="row g-3">
    <div class="col-md-7"><label class="form-label campo-obrigatorio" for="med_id">Medicamento</label><select class="form-select" id="med_id" name="med_id" required><option value="">Selecione</option><?php foreach ($medicamentos as $medicamento): ?><option value="<?= (int) $medicamento['med_id'] ?>" <?= (string) ($compra['med_id'] ?? '') === (string) $medicamento['med_id'] ? 'selected' : '' ?>><?= escapar($medicamento['med_nome'] . ($medicamento['med_apresentacao'] ? ' — ' . $medicamento['med_apresentacao'] : '') . (!$medicamento['med_ativo'] ? ' (inativo)' : '')) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-5"><label class="form-label campo-obrigatorio" for="com_data_compra">Data da compra</label><input class="form-control" type="date" id="com_data_compra" name="com_data_compra" value="<?= escapar($compra['com_data_compra'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label" for="com_quantidade">Quantidade</label><input class="form-control" type="number" step="0.01" min="0.01" id="com_quantidade" name="com_quantidade" value="<?= escapar(formatar_decimal_input($compra['com_quantidade'] ?? '')) ?>"></div>
    <div class="col-md-4"><label class="form-label" for="com_valor">Valor pago</label><div class="input-group"><span class="input-group-text">R$</span><input class="form-control" type="number" step="0.01" min="0" id="com_valor" name="com_valor" value="<?= escapar(formatar_decimal_input($compra['com_valor'] ?? '')) ?>"></div></div>
    <div class="col-md-4"><label class="form-label" for="com_data_validade">Validade</label><input class="form-control" type="date" id="com_data_validade" name="com_data_validade" value="<?= escapar($compra['com_data_validade'] ?? '') ?>"></div>
    <div class="col-md-6"><label class="form-label" for="com_lote">Lote</label><input class="form-control" id="com_lote" name="com_lote" maxlength="80" value="<?= escapar($compra['com_lote'] ?? '') ?>"></div>
    <div class="col-12"><label class="form-label" for="com_observacoes">Observações</label><textarea class="form-control" id="com_observacoes" name="com_observacoes" rows="3" maxlength="2000"><?= escapar($compra['com_observacoes'] ?? '') ?></textarea></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-outline-secondary" href="<?= escapar(url('/medicamentos/compras')) ?>">Cancelar</a><button class="btn btn-success" type="submit">Salvar compra</button></div></div></div></form><?php endif; ?>

