<?php $editando = !empty($exercicio['exe_id']); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar exercício' : 'Novo exercício' ?></h1><p class="text-secondary mb-0">O catálogo permite acompanhar evolução entre planos.</p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/exercicios')) ?>">Voltar</a></div>
<form action="<?= escapar(url('/treinos/exercicios/salvar')) ?>" method="post"><?= campo_csrf() ?><?php if ($editando): ?><input type="hidden" name="exe_id" value="<?= (int) $exercicio['exe_id'] ?>"><?php endif; ?>
<div class="card"><div class="card-body p-4"><div class="row g-3">
<div class="col-md-7"><label class="form-label campo-obrigatorio" for="exe_nome">Nome</label><input class="form-control" id="exe_nome" name="exe_nome" maxlength="120" value="<?= escapar($exercicio['exe_nome'] ?? '') ?>" required autofocus></div>
<div class="col-md-5"><label class="form-label campo-obrigatorio" for="exe_tipo">Tipo</label><select class="form-select" id="exe_tipo" name="exe_tipo" required><?php foreach (TIPOS_EXERCICIO as $valor => $rotulo): ?><option value="<?= escapar($valor) ?>" <?= ($exercicio['exe_tipo'] ?? '') === $valor ? 'selected' : '' ?>><?= escapar($rotulo) ?></option><?php endforeach; ?></select></div>
<div class="col-12"><label class="form-label" for="exe_grupo_muscular">Grupo muscular ou categoria</label><input class="form-control" id="exe_grupo_muscular" name="exe_grupo_muscular" maxlength="80" value="<?= escapar($exercicio['exe_grupo_muscular'] ?? '') ?>" placeholder="Ex.: Peitoral, Quadríceps, Corrida"></div>
<div class="col-12"><label class="form-label" for="exe_observacoes">Observações</label><textarea class="form-control" id="exe_observacoes" name="exe_observacoes" rows="3"><?= escapar($exercicio['exe_observacoes'] ?? '') ?></textarea></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="exe_ativo" name="exe_ativo" value="1" <?= !empty($exercicio['exe_ativo']) ? 'checked' : '' ?>><label class="form-check-label" for="exe_ativo">Exercício ativo</label></div></div>
</div></div></div><div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/exercicios')) ?>">Cancelar</a><button class="btn btn-success" type="submit">Salvar exercício</button></div></form>
