<?php $editando = !empty($plano['ptr_id']); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar plano de treino' : 'Novo plano de treino' ?></h1><p class="text-secondary mb-0">Defina o ciclo; os treinos serão adicionados em seguida.</p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/planos')) ?>">Voltar</a></div>
<form action="<?= escapar(url('/treinos/planos/salvar')) ?>" method="post"><?= campo_csrf() ?><?php if ($editando): ?><input type="hidden" name="ptr_id" value="<?= (int) $plano['ptr_id'] ?>"><?php endif; ?>
<div class="card"><div class="card-body p-4"><div class="row g-3">
<div class="col-md-7"><label class="form-label campo-obrigatorio" for="ptr_nome">Nome do plano</label><input class="form-control" id="ptr_nome" name="ptr_nome" maxlength="120" value="<?= escapar($plano['ptr_nome'] ?? '') ?>" required autofocus></div>
<div class="col-md-5"><label class="form-label" for="ptr_objetivo">Objetivo</label><input class="form-control" id="ptr_objetivo" name="ptr_objetivo" maxlength="160" value="<?= escapar($plano['ptr_objetivo'] ?? '') ?>" placeholder="Ex.: Hipertrofia e condicionamento"></div>
<div class="col-md-6"><label class="form-label campo-obrigatorio" for="ptr_data_inicio">Início</label><input class="form-control" type="date" id="ptr_data_inicio" name="ptr_data_inicio" value="<?= escapar($plano['ptr_data_inicio'] ?? '') ?>" required></div>
<div class="col-md-6"><label class="form-label" for="ptr_data_fim">Fim</label><input class="form-control" type="date" id="ptr_data_fim" name="ptr_data_fim" value="<?= escapar($plano['ptr_data_fim'] ?? '') ?>"></div>
<div class="col-12"><label class="form-label" for="ptr_orientacoes">Orientações gerais</label><textarea class="form-control" id="ptr_orientacoes" name="ptr_orientacoes" rows="4"><?= escapar($plano['ptr_orientacoes'] ?? '') ?></textarea></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="ptr_ativo" name="ptr_ativo" value="1" <?= !empty($plano['ptr_ativo']) ? 'checked' : '' ?>><label class="form-check-label" for="ptr_ativo">Plano ativo</label></div></div>
</div></div></div><div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/planos')) ?>">Cancelar</a><button class="btn btn-success" type="submit">Salvar plano</button></div></form>
