<?php
$situacao = SITUACOES_TREINO[$registro['trr_situacao']] ?? ['rotulo' => $registro['trr_situacao'], 'classe' => 'text-bg-secondary', 'icone' => 'bi-circle'];
$realizadosPorPlanejado = [];
$extras = [];
foreach ($exercicios as $exercicio) {
    $planejadoId = (int) ($exercicio['exr_exp_id_snapshot'] ?? $exercicio['exp_id'] ?? 0);
    if ($planejadoId) {
        $realizadosPorPlanejado[$planejadoId] = $exercicio;
    } else {
        $extras[] = $exercicio;
    }
}
?>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><div class="d-flex align-items-center gap-2"><h1 class="h3 mb-1"><?= escapar($registro['trr_treino_nome']) ?></h1><span class="badge <?= escapar($situacao['classe']) ?>"><?= escapar($situacao['rotulo']) ?></span></div><p class="text-secondary mb-0"><?= escapar(formatar_data($registro['trr_data'])) ?><?= $registro['trr_hora_inicio'] ? ' · ' . escapar(substr($registro['trr_hora_inicio'], 0, 5)) : '' ?></p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/historico')) ?>">Histórico</a><a class="btn btn-outline-primary" href="<?= escapar(url('/treinos/realizados/formulario?id=' . $registro['trr_id'])) ?>">Editar</a></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-secondary">Aderência</div><div class="h4 mb-0"><?= $resumo['aderencia'] === null ? '—' : $resumo['aderencia'] . '%' ?></div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-secondary">Séries</div><div class="h4 mb-0"><?= $resumo['series_concluidas'] ?> / <?= $resumo['series_planejadas'] ?></div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-secondary">Séries extras</div><div class="h4 mb-0"><?= $resumo['series_extras'] ?></div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-secondary">Volume</div><div class="h4 mb-0"><?= formatar_decimal($resumo['volume']) ?> kg</div></div></div></div>
<?php if ($registro['trr_situacao'] === 'nao_realizado'): ?><div class="alert alert-danger">Este treino foi marcado como não realizado.</div><?php else: ?><div class="vstack gap-4"><?php foreach (($registro['planejado']['exercicios'] ?? []) as $planejado): ?><?php $realizado = $realizadosPorPlanejado[(int) $planejado['exp_id']] ?? null; ?><section class="card"><div class="card-header bg-white py-3"><h2 class="h5 mb-0"><?= escapar($planejado['nome']) ?></h2><span class="small text-secondary">Planejado: <?= (int) $planejado['series'] ?> série(s)<?= $planejado['repeticoes_min'] ? ' · ' . (int) $planejado['repeticoes_min'] . ($planejado['repeticoes_max'] && $planejado['repeticoes_max'] != $planejado['repeticoes_min'] ? '–' . (int) $planejado['repeticoes_max'] : '') . ' rep.' : '' ?><?= $planejado['carga_alvo'] !== null ? ' · ' . formatar_decimal($planejado['carga_alvo']) . ' kg' : '' ?></span></div><div class="card-body"><?php if (!$realizado): ?><div class="alert alert-warning mb-0">Exercício não realizado.</div><?php else: ?><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Série</th><th>Repetições</th><th>Carga</th><th>Duração</th><th>Distância</th><th>Situação</th></tr></thead><tbody><?php foreach ($realizado['series'] as $serie): ?><tr><td><?= (int) $serie['srr_numero'] ?></td><td><?= $serie['srr_repeticoes'] === null ? '—' : (int) $serie['srr_repeticoes'] ?></td><td><?= $serie['srr_carga_kg'] === null ? '—' : formatar_decimal($serie['srr_carga_kg']) . ' kg' ?></td><td><?= escapar(formatar_duracao_segundos($serie['srr_duracao_segundos'])) ?></td><td><?= $serie['srr_distancia_km'] === null ? '—' : formatar_decimal($serie['srr_distancia_km']) . ' km' ?></td><td><span class="badge <?= $serie['srr_concluida'] ? 'text-bg-success' : 'text-bg-secondary' ?>"><?= $serie['srr_concluida'] ? 'Concluída' : 'Não concluída' ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></section><?php endforeach; ?>
<?php foreach ($extras as $realizado): ?><section class="card border-info"><div class="card-header bg-white"><h2 class="h5 mb-0"><?= escapar($realizado['exr_nome']) ?> <span class="badge text-bg-info">Extra</span></h2></div><div class="card-body"><?= count($realizado['series']) ?> série(s) registrada(s)</div></section><?php endforeach; ?></div><?php endif; ?>
<?php if ($registro['trr_observacoes']): ?><div class="alert alert-light border mt-4"><strong>Observações:</strong><br><?= nl2br(escapar($registro['trr_observacoes'])) ?></div><?php endif; ?>
