<?php
$editando = !empty($registro['trr_id']);
$situacaoAtual = $registro['trr_situacao'] ?? 'em_andamento';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar treino realizado' : 'Registrar treino' ?></h1><p class="text-secondary mb-0"><?= escapar($planejado['nome'] ?? $registro['trr_treino_nome'] ?? 'Treino') ?></p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos?data=' . ($registro['trr_data'] ?? date('Y-m-d')))) ?>">Voltar</a></div>
<form action="<?= escapar(url('/treinos/realizados/salvar')) ?>" method="post" id="form-treino-realizado"><?= campo_csrf() ?><?php if ($editando): ?><input type="hidden" name="trr_id" value="<?= (int) $registro['trr_id'] ?>"><?php endif; ?><input type="hidden" name="trp_id" value="<?= (int) ($registro['trp_id'] ?? 0) ?>">
<div class="card mb-4"><div class="card-body p-4"><div class="row g-3">
<div class="col-md-4"><label class="form-label campo-obrigatorio" for="trr_data">Data</label><input class="form-control" type="date" id="trr_data" name="trr_data" max="<?= escapar(date('Y-m-d')) ?>" value="<?= escapar($registro['trr_data'] ?? date('Y-m-d')) ?>" required></div>
<div class="col-md-4"><label class="form-label" for="trr_hora_inicio">Início</label><input class="form-control" type="time" id="trr_hora_inicio" name="trr_hora_inicio" value="<?= escapar($registro['trr_hora_inicio'] ?? '') ?>"></div>
<div class="col-md-4"><label class="form-label" for="trr_hora_fim">Fim</label><input class="form-control" type="time" id="trr_hora_fim" name="trr_hora_fim" value="<?= escapar($registro['trr_hora_fim'] ?? '') ?>"></div>
<div class="col-md-4"><label class="form-label campo-obrigatorio" for="trr_situacao">Situação</label><select class="form-select" id="trr_situacao" name="trr_situacao" required><?php foreach (SITUACOES_TREINO as $valor => $dados): ?><option value="<?= escapar($valor) ?>" <?= $situacaoAtual === $valor ? 'selected' : '' ?>><?= escapar($dados['rotulo']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label" for="trr_esforco_percebido">Esforço percebido (0–10)</label><select class="form-select" id="trr_esforco_percebido" name="trr_esforco_percebido"><option value="">Não informar</option><?php for ($nivel = 0; $nivel <= 10; $nivel++): ?><option value="<?= $nivel ?>" <?= (string) ($registro['trr_esforco_percebido'] ?? '') === (string) $nivel ? 'selected' : '' ?>><?= $nivel ?></option><?php endfor; ?></select></div>
<div class="col-md-4"><label class="form-label" for="trr_energia">Energia (0–10)</label><select class="form-select" id="trr_energia" name="trr_energia"><option value="">Não informar</option><?php for ($nivel = 0; $nivel <= 10; $nivel++): ?><option value="<?= $nivel ?>" <?= (string) ($registro['trr_energia'] ?? '') === (string) $nivel ? 'selected' : '' ?>><?= $nivel ?></option><?php endfor; ?></select></div>
<div class="col-12"><label class="form-label" for="trr_observacoes">Observações da sessão</label><textarea class="form-control" id="trr_observacoes" name="trr_observacoes" rows="3" maxlength="2000"><?= escapar($registro['trr_observacoes'] ?? '') ?></textarea></div>
</div></div></div>
<div id="bloco-exercicios-realizados">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-2"><div><h2 class="h5 mb-0">Exercícios e séries</h2><span class="small text-secondary">Marque apenas as séries efetivamente concluídas.</span></div><button class="btn btn-outline-success adicionar-exercicio-realizado" id="adicionar-exercicio-realizado" type="button"><i class="bi bi-plus-lg me-1"></i>Exercício extra</button></div>
<div id="exercicios-realizados" class="vstack gap-4"><?php foreach ($exerciciosRealizados as $indice => $exercicio): ?><?php $series = $exercicio['series'] ?: [['srr_numero' => 1, 'srr_concluida' => 1]]; ?>
<section class="card exercicio-realizado" data-indice="<?= $indice ?>"><div class="card-header bg-white d-flex justify-content-between align-items-center gap-2 py-3"><div><h3 class="h5 mb-0"><?= escapar($exercicio['exr_nome']) ?></h3><span class="small text-secondary"><?= escapar(TIPOS_EXERCICIO[$exercicio['exr_tipo']] ?? $exercicio['exr_tipo']) ?></span></div><button class="btn btn-sm btn-outline-danger btn-icone remover-exercicio-realizado" type="button"><i class="bi bi-trash"></i></button></div>
<div class="card-body"><input type="hidden" name="exr_exe_id[]" value="<?= (int) ($exercicio['exe_id'] ?? 0) ?>"><input type="hidden" name="exr_exp_id[]" value="<?= (int) ($exercicio['exp_id'] ?? 0) ?>"><input type="hidden" name="exr_exp_id_snapshot[]" value="<?= (int) ($exercicio['exr_exp_id_snapshot'] ?? $exercicio['exp_id'] ?? 0) ?>"><input type="hidden" name="exr_nome[]" value="<?= escapar($exercicio['exr_nome']) ?>"><input type="hidden" name="exr_tipo[]" value="<?= escapar($exercicio['exr_tipo']) ?>">
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Série</th><th>Rep.</th><th>Carga (kg)</th><th>Duração (s)</th><th>Distância (km)</th><th>Concluída</th><th></th></tr></thead><tbody class="series-realizadas"><?php foreach ($series as $serieIndice => $serie): ?><tr class="serie-realizada"><td class="numero-serie"><?= $serieIndice + 1 ?></td><td><input class="form-control form-control-sm" type="number" min="0" name="srr_repeticoes[<?= $indice ?>][<?= $serieIndice ?>]" value="<?= escapar($serie['srr_repeticoes'] ?? '') ?>"></td><td><input class="form-control form-control-sm" type="number" step="0.01" min="0" name="srr_carga_kg[<?= $indice ?>][<?= $serieIndice ?>]" value="<?= escapar(formatar_decimal_input($serie['srr_carga_kg'] ?? '')) ?>"></td><td><input class="form-control form-control-sm" type="number" min="0" name="srr_duracao_segundos[<?= $indice ?>][<?= $serieIndice ?>]" value="<?= escapar($serie['srr_duracao_segundos'] ?? '') ?>"></td><td><input class="form-control form-control-sm" type="number" step="0.01" min="0" name="srr_distancia_km[<?= $indice ?>][<?= $serieIndice ?>]" value="<?= escapar(formatar_decimal_input($serie['srr_distancia_km'] ?? '')) ?>"></td><td class="text-center"><input class="form-check-input" type="checkbox" name="srr_concluida[<?= $indice ?>][<?= $serieIndice ?>]" value="1" <?= !empty($serie['srr_concluida']) ? 'checked' : '' ?>></td><td><button class="btn btn-sm btn-outline-danger btn-icone remover-serie-realizada" type="button"><i class="bi bi-x-lg"></i></button></td></tr><?php endforeach; ?></tbody></table></div>
<button class="btn btn-sm btn-outline-success adicionar-serie-realizada" type="button"><i class="bi bi-plus-lg me-1"></i>Adicionar série</button><div class="mt-3"><label class="form-label">Observações do exercício</label><input class="form-control" name="exr_observacoes[]" maxlength="500" value="<?= escapar($exercicio['exr_observacoes'] ?? '') ?>"></div></div></section>
<?php endforeach; ?></div></div>
<div class="d-flex flex-wrap justify-content-end gap-2 mt-4"><button class="btn btn-outline-success adicionar-exercicio-realizado me-auto" type="button"><i class="bi bi-plus-lg me-1"></i>Adicionar exercício</button><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos?data=' . ($registro['trr_data'] ?? date('Y-m-d')))) ?>">Cancelar</a><button class="btn btn-success" type="submit">Salvar treino</button></div></form>
<?php if ($editando): ?><form class="text-end mt-2" action="<?= escapar(url('/treinos/realizados/excluir')) ?>" method="post"><?= campo_csrf() ?><input type="hidden" name="trr_id" value="<?= (int) $registro['trr_id'] ?>"><button class="btn btn-sm btn-outline-danger" type="submit" data-confirmar="Excluir este treino realizado?"><i class="bi bi-trash me-1"></i>Excluir registro</button></form><?php endif; ?>
<template id="modelo-exercicio-realizado"><section class="card exercicio-realizado" data-indice="__INDEX__"><div class="card-header bg-white d-flex justify-content-between align-items-center gap-2 py-3"><div class="flex-grow-1"><label class="form-label campo-obrigatorio">Exercício extra</label><select class="form-select exercicio-extra-select js-select2-treino" name="exr_exe_id[]" data-placeholder="Pesquise um exercício" required><option value="">Selecione</option><?php foreach ($exercicios as $exercicio): ?><?php if ($exercicio['exe_ativo']): ?><option value="<?= (int) $exercicio['exe_id'] ?>" data-nome="<?= escapar($exercicio['exe_nome']) ?>" data-tipo="<?= escapar($exercicio['exe_tipo']) ?>"><?= escapar($exercicio['exe_nome']) ?></option><?php endif; ?><?php endforeach; ?></select></div><button class="btn btn-sm btn-outline-danger btn-icone remover-exercicio-realizado" type="button"><i class="bi bi-trash"></i></button></div><div class="card-body"><input type="hidden" name="exr_exp_id[]" value="0"><input type="hidden" name="exr_exp_id_snapshot[]" value="0"><input class="exr-nome" type="hidden" name="exr_nome[]" value=""><input class="exr-tipo" type="hidden" name="exr_tipo[]" value="outro"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Série</th><th>Rep.</th><th>Carga (kg)</th><th>Duração (s)</th><th>Distância (km)</th><th>Concluída</th><th></th></tr></thead><tbody class="series-realizadas"></tbody></table></div><button class="btn btn-sm btn-outline-success adicionar-serie-realizada" type="button"><i class="bi bi-plus-lg me-1"></i>Adicionar série</button><div class="mt-3"><label class="form-label">Observações do exercício</label><input class="form-control" name="exr_observacoes[]" maxlength="500"></div></div></section></template>
