<?php
$editando = !empty($treino['trp_id']);
if (!$itens) {
    $itens = [['exe_id' => '', 'series' => 3, 'repeticoes_min' => '', 'repeticoes_max' => '', 'carga_alvo_informada' => '', 'descanso_segundos' => '', 'duracao_segundos' => '', 'distancia_km_informada' => '', 'observacoes' => '']];
}
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar treino planejado' : 'Novo treino planejado' ?></h1><p class="text-secondary mb-0"><?= escapar($plano['ptr_nome']) ?></p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/planos/detalhes?id=' . $plano['ptr_id'])) ?>">Voltar</a></div>
<?php if (!$exercicios): ?><div class="alert alert-warning">Cadastre pelo menos um exercício antes de montar o treino. <a href="<?= escapar(url('/treinos/exercicios/formulario')) ?>">Cadastrar exercício</a>.</div><?php endif; ?>
<form action="<?= escapar(url('/treinos/planejados/salvar')) ?>" method="post" id="form-treino-planejado"><?= campo_csrf() ?><input type="hidden" name="ptr_id" value="<?= (int) $plano['ptr_id'] ?>"><?php if ($editando): ?><input type="hidden" name="trp_id" value="<?= (int) $treino['trp_id'] ?>"><?php endif; ?>
<div class="card mb-4"><div class="card-body p-4"><div class="row g-3">
<div class="col-md-5"><label class="form-label campo-obrigatorio" for="trp_nome">Nome do treino</label><input class="form-control" id="trp_nome" name="trp_nome" maxlength="100" value="<?= escapar($treino['trp_nome'] ?? '') ?>" placeholder="Ex.: Treino A — Peito e tríceps" required></div>
<div class="col-md-4"><label class="form-label" for="trp_dia_semana">Dia da semana</label><select class="form-select" id="trp_dia_semana" name="trp_dia_semana"><option value="">Sem dia fixo</option><?php foreach (DIAS_SEMANA as $valor => $rotulo): ?><option value="<?= $valor ?>" <?= (string) ($treino['trp_dia_semana'] ?? '') === (string) $valor ? 'selected' : '' ?>><?= escapar($rotulo) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label" for="trp_ordem">Ordem</label><input class="form-control" type="number" min="0" max="999" id="trp_ordem" name="trp_ordem" value="<?= escapar($treino['trp_ordem'] ?? 0) ?>" required></div>
<div class="col-12"><label class="form-label" for="trp_orientacoes">Orientações do treino</label><textarea class="form-control" id="trp_orientacoes" name="trp_orientacoes" rows="3"><?= escapar($treino['trp_orientacoes'] ?? '') ?></textarea></div>
</div></div></div>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-2"><div><h2 class="h5 mb-0">Exercícios planejados</h2><span class="small text-secondary">Metas vazias não serão cobradas no registro.</span></div><button class="btn btn-outline-success adicionar-exercicio-planejado" id="adicionar-exercicio-planejado" type="button" <?= !$exercicios ? 'disabled' : '' ?>><i class="bi bi-plus-lg me-1"></i>Adicionar exercício</button></div>
<div id="exercicios-planejados" class="vstack gap-3"><?php foreach ($itens as $item): ?>
<div class="card exercicio-planejado"><div class="card-body"><div class="row g-3">
<div class="col-md-5"><label class="form-label campo-obrigatorio">Exercício</label><select class="form-select js-select2-treino" name="exe_id[]" data-placeholder="Pesquise um exercício" required><option value="">Selecione</option><?php foreach ($exercicios as $exercicio): ?><option value="<?= (int) $exercicio['exe_id'] ?>" <?= (int) ($item['exe_id'] ?? 0) === (int) $exercicio['exe_id'] ? 'selected' : '' ?>><?= escapar($exercicio['exe_nome']) ?><?= $exercicio['exe_grupo_muscular'] ? ' · ' . escapar($exercicio['exe_grupo_muscular']) : '' ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label">Séries</label><input class="form-control" type="number" min="1" max="99" name="exp_series[]" value="<?= (int) ($item['exp_series'] ?? $item['series'] ?? 1) ?>" required></div>
<div class="col-md-2"><label class="form-label">Rep. mín.</label><input class="form-control" type="number" min="1" max="9999" name="exp_repeticoes_min[]" value="<?= escapar($item['exp_repeticoes_min'] ?? $item['repeticoes_min'] ?? '') ?>"></div>
<div class="col-md-2"><label class="form-label">Rep. máx.</label><input class="form-control" type="number" min="1" max="9999" name="exp_repeticoes_max[]" value="<?= escapar($item['exp_repeticoes_max'] ?? $item['repeticoes_max'] ?? '') ?>"></div>
<div class="col-md-1 text-end"><label class="form-label d-block">&nbsp;</label><button class="btn btn-outline-danger btn-icone remover-exercicio-planejado" type="button"><i class="bi bi-trash"></i></button></div>
<div class="col-md-3"><label class="form-label">Carga-alvo (kg)</label><input class="form-control" type="number" step="0.01" min="0" name="exp_carga_alvo[]" value="<?= escapar(formatar_decimal_input($item['exp_carga_alvo'] ?? $item['carga_alvo_informada'] ?? '')) ?>"></div>
<div class="col-md-3"><label class="form-label">Descanso (segundos)</label><input class="form-control" type="number" min="0" name="exp_descanso_segundos[]" value="<?= escapar($item['exp_descanso_segundos'] ?? $item['descanso_segundos'] ?? '') ?>"></div>
<div class="col-md-3"><label class="form-label">Duração-alvo (segundos)</label><input class="form-control" type="number" min="0" name="exp_duracao_segundos[]" value="<?= escapar($item['exp_duracao_segundos'] ?? $item['duracao_segundos'] ?? '') ?>"></div>
<div class="col-md-3"><label class="form-label">Distância-alvo (km)</label><input class="form-control" type="number" step="0.01" min="0" name="exp_distancia_km[]" value="<?= escapar(formatar_decimal_input($item['exp_distancia_km'] ?? $item['distancia_km_informada'] ?? '')) ?>"></div>
<div class="col-12"><label class="form-label">Observações</label><input class="form-control" name="exp_observacoes[]" maxlength="500" value="<?= escapar($item['exp_observacoes'] ?? $item['observacoes'] ?? '') ?>" placeholder="Técnica, cadência, aquecimento ou adaptação"></div>
</div></div></div><?php endforeach; ?></div>
<div class="d-flex flex-wrap justify-content-end gap-2 mt-4"><button class="btn btn-outline-success adicionar-exercicio-planejado me-auto" type="button" <?= !$exercicios ? 'disabled' : '' ?>><i class="bi bi-plus-lg me-1"></i>Adicionar exercício</button><a class="btn btn-outline-secondary" href="<?= escapar(url('/treinos/planos/detalhes?id=' . $plano['ptr_id'])) ?>">Cancelar</a><button class="btn btn-success" type="submit" <?= !$exercicios ? 'disabled' : '' ?>>Salvar treino</button></div>
</form>
<template id="modelo-exercicio-planejado"><div class="card exercicio-planejado"><div class="card-body"><div class="row g-3">
<div class="col-md-5"><label class="form-label campo-obrigatorio">Exercício</label><select class="form-select js-select2-treino" name="exe_id[]" data-placeholder="Pesquise um exercício" required><option value="">Selecione</option><?php foreach ($exercicios as $exercicio): ?><?php if ($exercicio['exe_ativo']): ?><option value="<?= (int) $exercicio['exe_id'] ?>"><?= escapar($exercicio['exe_nome']) ?><?= $exercicio['exe_grupo_muscular'] ? ' · ' . escapar($exercicio['exe_grupo_muscular']) : '' ?></option><?php endif; ?><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label">Séries</label><input class="form-control" type="number" min="1" max="99" name="exp_series[]" value="3" required></div>
<div class="col-md-2"><label class="form-label">Rep. mín.</label><input class="form-control" type="number" min="1" max="9999" name="exp_repeticoes_min[]"></div>
<div class="col-md-2"><label class="form-label">Rep. máx.</label><input class="form-control" type="number" min="1" max="9999" name="exp_repeticoes_max[]"></div>
<div class="col-md-1 text-end"><label class="form-label d-block">&nbsp;</label><button class="btn btn-outline-danger btn-icone remover-exercicio-planejado" type="button"><i class="bi bi-trash"></i></button></div>
<div class="col-md-3"><label class="form-label">Carga-alvo (kg)</label><input class="form-control" type="number" step="0.01" min="0" name="exp_carga_alvo[]"></div><div class="col-md-3"><label class="form-label">Descanso (segundos)</label><input class="form-control" type="number" min="0" name="exp_descanso_segundos[]"></div><div class="col-md-3"><label class="form-label">Duração-alvo (segundos)</label><input class="form-control" type="number" min="0" name="exp_duracao_segundos[]"></div><div class="col-md-3"><label class="form-label">Distância-alvo (km)</label><input class="form-control" type="number" step="0.01" min="0" name="exp_distancia_km[]"></div><div class="col-12"><label class="form-label">Observações</label><input class="form-control" name="exp_observacoes[]" maxlength="500"></div>
</div></div></div></template>
