<?php $editando = !empty($compra['cps_id']); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar compra' : 'Registrar compra' ?></h1><p class="text-secondary mb-0">Guarde os dados da aquisição e validade.</p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/suplementos/compras')) ?>">Voltar</a></div>
<?php if (!$suplementos): ?><div class="alert alert-warning">Cadastre um suplemento antes de registrar uma compra. <a href="<?= escapar(url('/suplementos/formulario')) ?>">Cadastrar agora</a>.</div><?php else: ?>
<form action="<?= escapar(url('/suplementos/compras/salvar')) ?>" method="post"><?= campo_csrf() ?><?php if ($editando): ?><input type="hidden" name="cps_id" value="<?= (int) $compra['cps_id'] ?>"><?php endif; ?>
<div class="card"><div class="card-body p-4"><div class="row g-3">
    <div class="col-md-7"><label class="form-label campo-obrigatorio" for="sup_id">Suplemento</label><select class="form-select" id="sup_id" name="sup_id" required><option value="">Selecione</option><?php foreach ($suplementos as $suplemento): ?><option value="<?= (int) $suplemento['sup_id'] ?>" <?= (string) ($compra['sup_id'] ?? '') === (string) $suplemento['sup_id'] ? 'selected' : '' ?>><?= escapar($suplemento['sup_nome'] . ($suplemento['sup_apresentacao'] ? ' — ' . $suplemento['sup_apresentacao'] : '') . (!$suplemento['sup_ativo'] ? ' (inativo)' : '')) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-5"><label class="form-label campo-obrigatorio" for="cps_data_compra">Data da compra</label><input class="form-control" type="date" id="cps_data_compra" name="cps_data_compra" value="<?= escapar($compra['cps_data_compra'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label" for="cps_quantidade">Quantidade</label><input class="form-control" type="number" step="0.01" min="0.01" id="cps_quantidade" name="cps_quantidade" value="<?= escapar(formatar_decimal_input($compra['cps_quantidade'] ?? '')) ?>"></div>
    <div class="col-md-4"><label class="form-label" for="cps_valor">Valor pago</label><div class="input-group"><span class="input-group-text">R$</span><input class="form-control" type="number" step="0.01" min="0" id="cps_valor" name="cps_valor" value="<?= escapar(formatar_decimal_input($compra['cps_valor'] ?? '')) ?>"></div></div>
    <div class="col-md-4"><label class="form-label" for="cps_data_validade">Validade</label><input class="form-control" type="date" id="cps_data_validade" name="cps_data_validade" value="<?= escapar($compra['cps_data_validade'] ?? '') ?>"></div>
    <div class="col-md-6"><label class="form-label" for="cps_lote">Lote</label><input class="form-control" id="cps_lote" name="cps_lote" maxlength="80" value="<?= escapar($compra['cps_lote'] ?? '') ?>"></div>
    <div class="col-12"><label class="form-label" for="cps_observacoes">Observações</label><textarea class="form-control" id="cps_observacoes" name="cps_observacoes" rows="3" maxlength="2000"><?= escapar($compra['cps_observacoes'] ?? '') ?></textarea></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-outline-secondary" href="<?= escapar(url('/suplementos/compras')) ?>">Cancelar</a><button class="btn btn-success" type="submit">Salvar compra</button></div></div></div></form><?php endif; ?>
