<?php $editando = !empty($plano['pal_id']); ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?= $editando ? 'Editar plano alimentar' : 'Novo plano alimentar' ?></h1><p class="text-secondary mb-0">Cadastre a vigência e as orientações gerais do plano.</p></div><a class="btn btn-outline-secondary" href="<?= escapar(url('/alimentacao/planos')) ?>">Voltar</a></div>
<form action="<?= escapar(url('/alimentacao/planos/salvar')) ?>" method="post"><?= campo_csrf() ?><?php if ($editando): ?><input type="hidden" name="pal_id" value="<?= (int) $plano['pal_id'] ?>"><?php endif; ?>
<div class="card"><div class="card-body p-4"><div class="row g-3">
    <div class="col-md-7"><label class="form-label campo-obrigatorio" for="pal_nome">Nome do plano</label><input class="form-control" id="pal_nome" name="pal_nome" maxlength="120" value="<?= escapar($plano['pal_nome'] ?? '') ?>" required autofocus placeholder="Ex.: Plano alimentar — agosto"></div>
    <div class="col-md-5"><label class="form-label" for="pal_profissional">Nutricionista ou profissional</label><input class="form-control" id="pal_profissional" name="pal_profissional" maxlength="120" value="<?= escapar($plano['pal_profissional'] ?? '') ?>"></div>
    <div class="col-md-4"><label class="form-label campo-obrigatorio" for="pal_data_inicio">Início da vigência</label><input class="form-control" type="date" id="pal_data_inicio" name="pal_data_inicio" value="<?= escapar($plano['pal_data_inicio'] ?? '') ?>" required></div>
    <div class="col-md-4"><label class="form-label" for="pal_data_fim">Fim da vigência</label><input class="form-control" type="date" id="pal_data_fim" name="pal_data_fim" value="<?= escapar($plano['pal_data_fim'] ?? '') ?>"></div>
    <div class="col-md-4 d-flex align-items-end pb-2"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" id="pal_ativo" name="pal_ativo" value="1" <?= !empty($plano['pal_ativo']) ? 'checked' : '' ?>><label class="form-check-label" for="pal_ativo">Plano ativo</label></div></div>
    <div class="col-12"><label class="form-label" for="pal_orientacoes">Orientações gerais</label><textarea class="form-control" id="pal_orientacoes" name="pal_orientacoes" rows="5" maxlength="5000" placeholder="Hidratação, horários, restrições e outras orientações"><?= escapar($plano['pal_orientacoes'] ?? '') ?></textarea></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-outline-secondary" href="<?= escapar(url('/alimentacao/planos')) ?>">Cancelar</a><button class="btn btn-success" type="submit">Salvar plano</button></div></div></div></form>
