<?php $situacao = situacao_plano_alimentar($plano); ?>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><div class="d-flex align-items-center gap-2"><h1 class="h3 mb-1"><?= escapar($plano['pal_nome']) ?></h1><span class="badge <?= escapar($situacao['classe']) ?>"><?= escapar($situacao['rotulo']) ?></span></div><p class="text-secondary mb-0"><?= escapar(formatar_data($plano['pal_data_inicio'])) ?> a <?= $plano['pal_data_fim'] ? escapar(formatar_data($plano['pal_data_fim'])) : 'sem data final' ?><?= $plano['pal_profissional'] ? ' · ' . escapar($plano['pal_profissional']) : '' ?></p></div>
    <div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?= escapar(url('/alimentacao/planos')) ?>">Planos</a><a class="btn btn-outline-primary" href="<?= escapar(url('/alimentacao/planos/formulario?id=' . $plano['pal_id'])) ?>"><i class="bi bi-pencil-square me-1"></i>Editar plano</a><a class="btn btn-success" href="<?= escapar(url('/alimentacao/refeicoes/formulario?plano=' . $plano['pal_id'])) ?>"><i class="bi bi-plus-lg me-1"></i>Nova refeição</a></div>
</div>
<?php if ($plano['pal_orientacoes']): ?><div class="alert alert-light border"><strong>Orientações gerais</strong><div class="mt-1"><?= nl2br(escapar($plano['pal_orientacoes'])) ?></div></div><?php endif; ?>
<?php if (!$plano['refeicoes']): ?>
    <div class="card"><div class="card-body p-5 text-center"><i class="bi bi-cup-hot display-5 text-success"></i><h2 class="h5 mt-3">Nenhuma refeição cadastrada</h2><p class="text-secondary">Adicione café da manhã, almoço, jantar ou qualquer outra refeição.</p><a class="btn btn-success" href="<?= escapar(url('/alimentacao/refeicoes/formulario?plano=' . $plano['pal_id'])) ?>">Adicionar refeição</a></div></div>
<?php else: ?><div class="vstack gap-3">
<?php foreach ($plano['refeicoes'] as $refeicao): ?><section class="card">
    <div class="card-header bg-white d-flex flex-wrap justify-content-between align-items-center gap-2 py-3"><div><h2 class="h5 mb-0"><?= escapar($refeicao['ref_nome']) ?></h2><?php if ($refeicao['ref_horario']): ?><span class="small text-secondary"><i class="bi bi-clock me-1"></i><?= escapar(substr($refeicao['ref_horario'], 0, 5)) ?></span><?php endif; ?></div><div><a class="btn btn-sm btn-outline-primary btn-icone" href="<?= escapar(url('/alimentacao/refeicoes/formulario?id=' . $refeicao['ref_id'])) ?>" title="Editar refeição" aria-label="Editar refeição"><i class="bi bi-pencil-square"></i></a> <form class="d-inline" action="<?= escapar(url('/alimentacao/refeicoes/excluir')) ?>" method="post"><?= campo_csrf() ?><input type="hidden" name="ref_id" value="<?= (int) $refeicao['ref_id'] ?>"><button class="btn btn-sm btn-outline-danger btn-icone" type="submit" data-confirmar="Excluir esta refeição e todos os seus alimentos?" title="Excluir refeição" aria-label="Excluir refeição"><i class="bi bi-trash"></i></button></form></div></div>
    <div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Alimento</th><th>Quantidade</th><th>Substituições</th></tr></thead><tbody>
        <?php foreach ($refeicao['itens'] as $item): ?><tr><td class="fw-semibold"><?= escapar($item['ita_alimento']) ?></td><td><?= $item['ita_quantidade'] === null ? '—' : formatar_decimal($item['ita_quantidade']) . ' ' . escapar(UNIDADES_ALIMENTO[$item['ita_unidade']] ?? ($item['ita_unidade'] ?: '')) ?></td><td><?= escapar($item['ita_substituicoes'] ?: '—') ?></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <?php if ($refeicao['ref_observacoes']): ?><div class="card-footer bg-light small"><i class="bi bi-info-circle me-1"></i><?= nl2br(escapar($refeicao['ref_observacoes'])) ?></div><?php endif; ?>
</section><?php endforeach; ?>
</div><?php endif; ?>
